### ISSUE TITLE
"./gradlew installDist" fails

### ISSUE THREAD

**Issue by jachinte** [TypeFox/theia-sprotty-example#18]
Hi,
I'm following the instructions from the README.md file, but I'm getting an error when executing `./gradlew installDist`.

Here is the complete stacktrace:

<details>
~/Development/repositories/theia-sprotty-example/server master
❯ ./gradlew installDist
Downloading https://services.gradle.org/distributions/gradle-3.5-bin.zip
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/miguel/.gradle/wrapper/dists/gradle-3.5-bin/daoimhu7k5rlo48ntmxw2ok3e/gradle-3.5-bin.zip to /Users/miguel/.gradle/wrapper/dists/gradle-3.5-bin/daoimhu7k5rlo48ntmxw2ok3e
Set executable permissions for: /Users/miguel/.gradle/wrapper/dists/gradle-3.5-bin/daoimhu7k5rlo48ntmxw2ok3e/gradle-3.5/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
:io.typefox.sprotty.example.multicore:generateXtextLanguage
Download https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext/2.12.0.M1/org.eclipse.xtext-2.12.0.M1Download https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.common.types/2.12.0.M1/org.eclipse.xtDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.xtext.generator/2.12.0.M1/org.eclipse.xtext.xtext.generator-2.12.0.M1.pom
Download https://jcenter.bintray.com/org/eclipse/emf/org.eclipse.emf.mwe2.launch/2.9.0.201605261059/org.eclipse.emf.mwe2.launch-2.9.0.201605261059.pom
Download https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.util/2.12.0.M1/org.eclipse.xtext.utilDownload https://jcenter.bintray.com/org/eclipse/xtend/org.eclipse.xtend.lib/2.12.0.M1/org.eclipse.xtend.lib-2Download https://jcenter.bintray.com/org/eclipse/emf/org.eclipse.emf.mwe2.language/2.9.0.201605261059/org.ecliDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.12.0.M1/org.eclipse.xtextDownload https://jcenter.bintray.com/org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.12.0.M1/org.eclipse.xtend.lib.macro-2.12.0.M1.pom
Download https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext/2.12.0.M1/org.eclipse.xtext-2.12.0.M1Download https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.common.types/2.12.0.M1/org.eclipse.xtDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.xtext.generator/2.12.0.M1/org.eclipseDownload https://jcenter.bintray.com/org/eclipse/emf/org.eclipse.emf.mwe2.launch/2.9.0.201605261059/org.eclipse.emf.mwe2.launch-2.9.0.201605261059.jar
Download https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.util/2.12.0.M1/org.eclipse.xtext.utilDownload https://jcenter.bintray.com/org/eclipse/xtend/org.eclipse.xtend.lib/2.12.0.M1/org.eclipse.xtend.lib-2Download https://jcenter.bintray.com/org/eclipse/platform/org.eclipse.osgi/3.11.2/org.eclipse.osgi-3.11.2.jar
Download https://jcenter.bintray.com/org/eclipse/emf/org.eclipse.emf.mwe2.language/2.9.0.201605261059/org.ecliDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.12.0.M1/org.eclipse.xtextDownload https://jcenter.bintray.com/org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.12.0.M1/org.eclipse.xtend0    [main] INFO  xt.xtext.generator.StandardLanguage  - Skipping registration of Xbase genmodel. Xbase is not on the classpath.
13   [main] INFO  text.xtext.generator.XtextGenerator  - Initializing Xtext generator
22   [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
160  [main] WARN  lipse.emf.mwe.utils.StandaloneSetup  - Skipping conflicting project antlr at 'archive:file:/Users/miguel/.gradle/caches/modules-2/files-2.1/org.antlr/antlr-runtime/3.2/31c746001016c6226bd7356c9f87a6a084ce3715/antlr-runtime-3.2.jar!/' and using 'archive:file:/Users/miguel/.gradle/caches/modules-2/files-2.1/org.xtext/antlr-generator/3.2.1/d3fa97d931949af341889c94f6455822674e52f2/antlr-generator-3.2.1.jar!/' instead.
166  [main] WARN  lipse.emf.mwe.utils.StandaloneSetup  - Skipping conflicting project antlr at 'archive:file:/Users/miguel/.gradle/caches/modules-2/files-2.1/org.xtext/antlr-generator/3.2.1/d3fa97d931949af341889c94f6455822674e52f2/antlr-generator-3.2.1.jar!/' and using 'archive:file:/Users/miguel/.gradle/caches/modules-2/files-2.1/antlr/antlr/2.7.7/83cd2cd674a217ade95a4bb83a8a14f351f48bd0/antlr-2.7.7.jar!/' instead.
172  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project io.typefox.sprotty.example.multicore at 'file:/Users/miguel/Development/repositories/theia-sprotty-example/server/io.typefox.sprotty.example.multicore/'
173  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project io.typefox.sprotty.example.multicore.ide at 'file:/Users/miguel/Development/repositories/theia-sprotty-example/server/io.typefox.sprotty.example.multicore.ide/'
185  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
1066 [main] INFO  text.xtext.generator.XtextGenerator  - Generating io.typefox.sprotty.example.multicore.MulticoreAllocation
3619 [main] INFO  nerator.ecore.EMFGeneratorFragment2  - Generating EMF model code
3837 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.typefox.io/sprotty/example/multicore/MulticoreAllocation' from 'platform:/resource/io.typefox.sprotty.example.multicore/model/generated/MulticoreAllocation.genmodel'
7987 [main] INFO  text.xtext.generator.XtextGenerator  - Generating common infrastructure
7991 [main] INFO  .emf.mwe2.runtime.workflow.Workflow  - Done.
:io.typefox.sprotty.example.multicore:generateXtext
Download https://jcenter.bintray.com/org/eclipse/xtend/org.eclipse.xtend.core/2.12.0.M1/org.eclipse.xtend.coreDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.xbase/2.12.0.M1/org.eclipse.xtext.xbase-2.12.0.M1.pom
Download https://jcenter.bintray.com/org/eclipse/xtend/org.eclipse.xtend.core/2.12.0.M1/org.eclipse.xtend.coreDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.xbase/2.12.0.M1/org.eclipse.xtext.xbaDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.java/2.12.0.M1/org.eclipse.xtext.javaDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.smap/2.12.0.M1/org.eclipse.xtext.smapDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.java/2.12.0.M1/org.eclipse.xtext.javaDownload https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.smap/2.12.0.M1/org.eclipse.xtext.smapWarning: NLS unused message: line_separator_platform_mac_os_9 in: org.eclipse.core.internal.runtime.messages
Warning: NLS missing message: auth_alreadySpecified in: org.eclipse.core.internal.runtime.messages
Warning: NLS missing message: plugin_unableToGetActivator in: org.eclipse.core.internal.runtime.messages
:io.typefox.sprotty.example.multicore:compileJava
Note: /Users/miguel/Development/repositories/theia-sprotty-example/server/io.typefox.sprotty.example.multicore/build/xtend/main/io/typefox/sprotty/example/multicore/validation/MulticoreAllocationValidator.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:io.typefox.sprotty.example.multicore:processResources
:io.typefox.sprotty.example.multicore:classes
:io.typefox.sprotty.example.multicore:jar
:io.typefox.sprotty.example.multicore.ide:generateXtext
Download https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.ide/2.12.0.M1/org.eclipse.xtext.ide-2Download https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j/0.2.0/org.eclipse.lsp4j-0.2.0.pom
Download https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/elk/org.eclipse.elk.alg.layered/0Download https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j.generator/0.2.0/org.eclipse.lsp4j.genDownload https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc/0.2.0/org.eclipse.lsp4j.jsonrDownload https://jcenter.bintray.com/org/eclipse/xtend/org.eclipse.xtend.lib/2.12.0/org.eclipse.xtend.lib-2.12Download https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtend/org.eclipse.xtend.lib/2.13.Download https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtext/org.eclipse.xtext.xbase.libDownload https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtend/org.eclipse.xtend.lib.macro:io.typefox.sprotty.example.multicore.ide:generateXtext FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':io.typefox.sprotty.example.multicore.ide:compileClasspath'.
> Could not find io.typefox.sprotty:diagram-server:0.1.0-SNAPSHOT.
  Searched in the following locations:
      https://jcenter.bintray.com/io/typefox/sprotty/diagram-server/0.1.0-SNAPSHOT/maven-metadata.xml
      https://jcenter.bintray.com/io/typefox/sprotty/diagram-server/0.1.0-SNAPSHOT/diagram-server-0.1.0-SNAPSHOT.pom
      https://jcenter.bintray.com/io/typefox/sprotty/diagram-server/0.1.0-SNAPSHOT/diagram-server-0.1.0-SNAPSHOT.jar
      file:/Users/miguel/.m2/repository/io/typefox/sprotty/diagram-server/0.1.0-SNAPSHOT/maven-metadata.xml
      file:/Users/miguel/.m2/repository/io/typefox/sprotty/diagram-server/0.1.0-SNAPSHOT/diagram-server-0.1.0-SNAPSHOT.pom
      file:/Users/miguel/.m2/repository/io/typefox/sprotty/diagram-server/0.1.0-SNAPSHOT/diagram-server-0.1.0-SNAPSHOT.jar
      https://oss.sonatype.org/content/repositories/snapshots/io/typefox/sprotty/diagram-server/0.1.0-SNAPSHOT/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/snapshots/io/typefox/sprotty/diagram-server/0.1.0-SNAPSHOT/diagram-server-0.1.0-SNAPSHOT.pom
      https://oss.sonatype.org/content/repositories/snapshots/io/typefox/sprotty/diagram-server/0.1.0-SNAPSHOT/diagram-server-0.1.0-SNAPSHOT.jar
  Required by:
      project :io.typefox.sprotty.example.multicore.ide
> Could not find io.typefox.sprotty:diagram-layout-engine:0.1.0-SNAPSHOT.
  Searched in the following locations:
      https://jcenter.bintray.com/io/typefox/sprotty/diagram-layout-engine/0.1.0-SNAPSHOT/maven-metadata.xml
      https://jcenter.bintray.com/io/typefox/sprotty/diagram-layout-engine/0.1.0-SNAPSHOT/diagram-layout-engine-0.1.0-SNAPSHOT.pom
      https://jcenter.bintray.com/io/typefox/sprotty/diagram-layout-engine/0.1.0-SNAPSHOT/diagram-layout-engine-0.1.0-SNAPSHOT.jar
      file:/Users/miguel/.m2/repository/io/typefox/sprotty/diagram-layout-engine/0.1.0-SNAPSHOT/maven-metadata.xml
      file:/Users/miguel/.m2/repository/io/typefox/sprotty/diagram-layout-engine/0.1.0-SNAPSHOT/diagram-layout-engine-0.1.0-SNAPSHOT.pom
      file:/Users/miguel/.m2/repository/io/typefox/sprotty/diagram-layout-engine/0.1.0-SNAPSHOT/diagram-layout-engine-0.1.0-SNAPSHOT.jar
      https://oss.sonatype.org/content/repositories/snapshots/io/typefox/sprotty/diagram-layout-engine/0.1.0-SNAPSHOT/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/snapshots/io/typefox/sprotty/diagram-layout-engine/0.1.0-SNAPSHOT/diagram-layout-engine-0.1.0-SNAPSHOT.pom
      https://oss.sonatype.org/content/repositories/snapshots/io/typefox/sprotty/diagram-layout-engine/0.1.0-SNAPSHOT/diagram-layout-engine-0.1.0-SNAPSHOT.jar
  Required by:
      project :io.typefox.sprotty.example.multicore.ide

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 28.862 secs
</details>

I'm using a Mac, Java 1.8.
Is it my mistake?

Thank you.

**Comment by JanKoehnlein** [comment]
Our fault, please pull the latest changes and retry.

**Comment by spoenemann** [comment]
We were using the 0.1.0-SNAPSHOT version of sprotty, which is no longer available. I switched to the released `0.1.0` version.

**Comment by jachinte** [comment]
Thanks. It worked, but now I'm having a problem preparing the Theia extension for the example DSL.
```
~/Development/repositories/theia-sprotty-example/theia-dsl-extension master
❯ yarn install
yarn install v0.17.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning theia-core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] 🚚  Fetching packages...
warning vscode-base-languageclient@0.0.1-alpha.2: The engine "vscode" appears to be invalid.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
$ npm run copy-ls && npm run build

> theia-dsl-extension@1.0.0 copy-ls /Users/miguel/Development/repositories/theia-sprotty-example/theia-dsl-extension
> rm -rf ./build && mkdir build && cp -r ../server/io.typefox.sprotty.example.multicore.ide/build/install/example-server ./build


> theia-dsl-extension@1.0.0 build /Users/miguel/Development/repositories/theia-sprotty-example/theia-dsl-extension
> tsc && npm run lint

src/browser/diagram/diagram-configuration.ts(8,34): error TS2307: Cannot find module 'sprotty/lib/utils/registry'.
src/browser/diagram/diagram-configuration.ts(22,42): error TS2339: Property 'register' does not exist on type 'DiagramConfigurationRegistry'.
src/browser/diagram/diagram-manager.ts(9,37): error TS2307: Cannot find module 'theia-core/lib/editor/browser'.
src/browser/diagram/diagram-manager.ts(12,98): error TS2307: Cannot find module 'theia-core/lib/application/browser'.
src/browser/diagram/diagram-manager.ts(13,17): error TS2307: Cannot find module 'theia-core/lib/application/common/uri'.
src/browser/diagram/diagram-manager.ts(16,50): error TS2307: Cannot find module 'theia-core/lib/application/common'.
src/browser/diagram/diagram-widget-registry.ts(9,17): error TS2307: Cannot find module 'theia-core/lib/application/common/uri'.
src/browser/diagram/diagram-widget-registry.ts(10,46): error TS2307: Cannot find module 'theia-core/lib/application/common'.
src/browser/diagram/diagram-widget.ts(9,99): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/diagram/diagram-widget.ts(12,17): error TS2307: Cannot find module 'theia-core/lib/application/common/uri'.
src/browser/diagram/diagram-widget.ts(35,23): error TS2339: Property 'handle' does not exist on type 'TheiaDiagramServer'.
src/browser/diagram/theia-diagram-server-connector.ts(8,31): error TS2307: Cannot find module 'theia-core/lib/editor/browser'.
src/browser/diagram/theia-diagram-server-connector.ts(11,23): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/diagram/theia-diagram-server-connector.ts(14,44): error TS2307: Cannot find module 'theia-core/lib/languages/browser'.
src/browser/diagram/theia-diagram-server-connector.ts(16,17): error TS2307: Cannot find module 'theia-core/lib/application/common/uri'.
src/browser/diagram/theia-diagram-server-connector.ts(31,13): error TS7006: Parameter 'lc' implicitly has an 'any' type.
src/browser/diagram/theia-diagram-server-connector.ts(36,13): error TS7006: Parameter 'err' implicitly has an 'any' type.
src/browser/diagram/theia-diagram-server-connector.ts(41,72): error TS2339: Property 'get' does not exist on type 'DiagramConfigurationRegistry'.
src/browser/diagram/theia-diagram-server-connector.ts(49,61): error TS7006: Parameter 'lc' implicitly has an 'any' type.
src/browser/diagram/theia-diagram-server-connector.ts(53,61): error TS7006: Parameter 'lc' implicitly has an 'any' type.
src/browser/diagram/theia-diagram-server-connector.ts(59,13): error TS7006: Parameter 'editorWidget' implicitly has an 'any' type.
src/browser/diagram/theia-diagram-server.ts(11,8): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/flow/di.config.ts(13,8): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/flow/flowmodel-factory.ts(11,8): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/flow/flowmodel-factory.ts(18,25): error TS2339: Property 'initializeChild' does not exist on type 'FlowModelFactory'.
src/browser/flow/flowmodel-factory.ts(20,25): error TS2339: Property 'initializeChild' does not exist on type 'FlowModelFactory'.
src/browser/flow/flowmodel-factory.ts(22,25): error TS2339: Property 'initializeChild' does not exist on type 'FlowModelFactory'.
src/browser/flow/flowmodel-factory.ts(29,25): error TS2339: Property 'initializeRoot' does not exist on type 'FlowModelFactory'.
src/browser/flow/flowmodel-factory.ts(31,25): error TS2339: Property 'initializeRoot' does not exist on type 'FlowModelFactory'.
src/browser/flow/flowmodel.ts(8,49): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/flow/flowmodel.ts(9,24): error TS2307: Cannot find module 'sprotty/lib/utils/geometry'.
src/browser/flow/kernel-color.ts(8,38): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/flow/views.tsx(9,98): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/flow/views.tsx(10,41): error TS2307: Cannot find module 'sprotty/lib/utils/geometry'.
src/browser/flow/views.tsx(24,43): error TS2339: Property 'hoverFeedback' does not exist on type 'TaskNode'.
src/browser/flow/views.tsx(25,42): error TS2339: Property 'selected' does not exist on type 'TaskNode'.
src/browser/flow/views.tsx(43,84): error TS2339: Property 'hoverFeedback' does not exist on type 'BarrierNode'.
src/browser/flow/views.tsx(43,120): error TS2339: Property 'selected' does not exist on type 'BarrierNode'.
src/browser/language/frontend-extension.ts(9,44): error TS2307: Cannot find module 'theia-core/lib/languages/browser'.
src/browser/language/frontend-extension.ts(14,62): error TS2307: Cannot find module 'theia-core/lib/application/browser'.
src/browser/language/language-client-contribution.ts(9,17): error TS2307: Cannot find module 'theia-core/lib/application/common/uri'.
src/browser/language/language-client-contribution.ts(10,37): error TS2307: Cannot find module 'theia-core/lib/application/browser'.
src/browser/language/language-client-contribution.ts(11,93): error TS2307: Cannot find module 'theia-core/lib/languages/browser'.
src/browser/language/language-client-contribution.ts(47,67): error TS7006: Parameter 'uri' implicitly has an 'any' type.
src/browser/processor/chipmodel-factory.ts(11,8): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/processor/chipmodel-factory.ts(23,35): error TS2339: Property 'initializeChild' does not exist on type 'ChipModelFactory'.
src/browser/processor/chipmodel-factory.ts(24,22): error TS2339: Property 'bounds' does not exist on type 'Core'.
src/browser/processor/chipmodel-factory.ts(33,29): error TS2339: Property 'initializeChild' does not exist on type 'ChipModelFactory'.
src/browser/processor/chipmodel-factory.ts(35,29): error TS2339: Property 'initializeChild' does not exist on type 'ChipModelFactory'.
src/browser/processor/chipmodel-factory.ts(37,29): error TS2339: Property 'initializeChild' does not exist on type 'ChipModelFactory'.
src/browser/processor/chipmodel-factory.ts(46,25): error TS2339: Property 'initializeRoot' does not exist on type 'ChipModelFactory'.
src/browser/processor/chipmodel-factory.ts(48,25): error TS2339: Property 'initializeRoot' does not exist on type 'ChipModelFactory'.
src/browser/processor/chipmodel.ts(13,8): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/processor/di.config.ts(12,8): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/processor/views.tsx(10,79): error TS2307: Cannot find module 'sprotty/lib'.
src/browser/processor/views.tsx(21,42): error TS2339: Property 'zoom' does not exist on type 'Processor'.
src/browser/processor/views.tsx(21,68): error TS2339: Property 'scroll' does not exist on type 'Processor'.
src/browser/processor/views.tsx(21,87): error TS2339: Property 'scroll' does not exist on type 'Processor'.
src/browser/processor/views.tsx(51,36): error TS2339: Property 'size' does not exist on type 'Core'.
src/browser/processor/views.tsx(52,37): error TS2339: Property 'size' does not exist on type 'Core'.
src/browser/processor/views.tsx(77,36): error TS2339: Property 'size' does not exist on type 'Core'.
src/browser/processor/views.tsx(78,37): error TS2339: Property 'size' does not exist on type 'Core'.
src/browser/processor/views.tsx(90,29): error TS2339: Property 'parent' does not exist on type 'Crossbar'.
src/browser/processor/views.tsx(91,32): error TS2339: Property 'parent' does not exist on type 'Crossbar'.
src/browser/processor/views.tsx(144,23): error TS2339: Property 'root' does not exist on type 'Channel'.
src/browser/processor/views.tsx(144,42): error TS2339: Property 'zoom' does not exist on type 'Processor'.
src/node/backend-extension.ts(9,89): error TS2307: Cannot find module 'theia-core/lib/languages/node'.
src/node/backend-extension.ts(30,39): error TS2339: Property 'createProcessStreamConnection' does not exist on type 'MultiCoreLanguageServerContribution'.
src/node/backend-extension.ts(31,14): error TS2339: Property 'forward' does not exist on type 'MultiCoreLanguageServerContribution'.

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! theia-dsl-extension@1.0.0 build: `tsc && npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the theia-dsl-extension@1.0.0 build script 'tsc && npm run lint'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the theia-dsl-extension package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && npm run lint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs theia-dsl-extension
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls theia-dsl-extension
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/miguel/Development/repositories/theia-sprotty-example/theia-dsl-extension/npm-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by JanKoehnlein** [comment]
Have you tried npm, version4?

**Comment by spoenemann** [comment]
I updated the example projects to use fixed versions for sprotty and theia. Also updated the README.

**Comment by jachinte** [comment]
@JanKoehnlein I upgraded npm but I didn't work.
@spoenemann  It worked, thanks.

Now, this is what I got in the browser:

![screen shot 2017-06-09 at 9 57 43 am](https://user-images.githubusercontent.com/1284036/26985937-79507612-4cfa-11e7-9fc5-4e87c96599ab.png)

It seems like there's a problem starting the backend:
```
❯ yarn run start:backend
yarn run v0.17.10
$ node ./lib/backend/main.js --root-dir=../workspace 
Error: No matching bindings found for serviceIdentifier: Symbol(LanguageServerContribution)
    at _createSubRequests (/Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/node_modules/inversify/lib/planning/planner.js:107:19)
    at Object.plan (/Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/node_modules/inversify/lib/planning/planner.js:126:5)
    at /Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/node_modules/inversify/lib/container/container.js:228:37
    at Container._get (/Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/node_modules/inversify/lib/container/container.js:221:44)
    at Container.getAll (/Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/node_modules/inversify/lib/container/container.js:189:21)
    at ContainerBasedContributionProvider.getContributions (/Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/node_modules/theia-core/lib/application/common/contribution-provider.js:24:48)
    at LanguagesBackendContribution.onStart (/Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/node_modules/theia-core/lib/languages/node/languages-backend-contribution.js:55:54)
    at /Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/node_modules/theia-core/lib/application/node/application.js:71:33
    at BackendApplication.start (/Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/node_modules/theia-core/lib/application/node/application.js:62:16)
    at Object.<anonymous> (/Users/miguel/Development/repositories/theia-sprotty-example-fixed/theia-app/lib/backend/main.js:54:13)
Theia app listening on port 3000.
^C
```

**Comment by JanKoehnlein** [comment]
By using npm I meant dropping yarn. Did you try that?

**Comment by jachinte** [comment]
Sorry @JanKoehnlein, didn't understand that. I tried it again, but the problem persists. Here are some screenshots:

![screen shot 2017-06-12 at 11 32 46 am](https://user-images.githubusercontent.com/1284036/27049085-13d2ffec-4f63-11e7-8b2a-eeadffcabd2b.png)
![screen shot 2017-06-12 at 11 33 17 am](https://user-images.githubusercontent.com/1284036/27049086-13eb4458-4f63-11e7-8b59-90d1c37e8209.png)

**Comment by JanKoehnlein** [comment]
Some things to try out
* Which version of npm are you using?  Try `npm --version`. Make sure it is 4.x, not 5.x neither 1-3.x.
* Does `npm install` in _theia-dsl-extension_ report an error (which is usually scrolled away by the following dependency tree) 
=>  Check `python --version`. It's likely python 2 is missing. Must be version 2, 3 won't work. It is needed by Theia.
*  Which version of inversifyJS is pulled into your node_modules? Have a look at `node_modules/inversify/package.json`. It must be 3.x.

**Comment by jachinte** [comment]
The error persists.
- I was using npm 5, but downgrade to 4.6.1.
- There's no error installing the extension. However, I'm using Python 2.7.10
- It uses inversify 3.3.0

If everything is working for you, it must be something on my machine. I'll try it in a different computer to see what happens.

**Comment by JanKoehnlein** [comment]
It works fine here. I tested on windows as well as on Mac.
If you could send a complete log, we could maybe help.

**Comment by jachinte** [comment]
I tested the example again and it works.
